/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package taller

object App {
    def main(args: Array[String]): Unit = {
        val objEjercicio = new ejercicioClase()
        val sol = objEjercicio.ejercicioClase(
            50,
            10,
            List(List(5,10,200), List(5,50,50), List(1,30,300))
        )
        print(sol)
    }
}
